### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by rajgoel** [mmoustafa/Chalkboard#1]
Very nice tool. Is this code under a free license?

**Comment by 0xmmo** [comment]
Yes! Feel free to use/alter. I will add a license file soon.

**Comment by rajgoel** [comment]
Great, thanks a lot. I just created a [plugin](https://github.com/rajgoel/reveal.js-plugins/tree/master/chalkboard) for [Reveal.js](https://github.com/hakimel/reveal.js) that uses your tool. Here is a [demo](http://courses.telematique.eu/reveal.js-plugins/chalkboard-demo.html).

**Comment by 0xmmo** [comment]
Pretty nifty implementation, would be awesome for presentations or lectures.
